To Do list: list structure
XsidX/todo-list-with-webpack pull request #1
Opened 2022-07-04 15:36 UTC by XsidX

For this project I:
-Have set up a new project with webpack.
-Created an index.html file and write your HTML markup here. 
-Created an index.js file and set an array of some simple to-do tasks (array of objects). Each task contains three keys:
description [string].
completed [bool].
index: [number].
-Written a function to iterate over the tasks array and populate an HTML list item element for each task.

2022-07-04 19:13 UTC, julie-ify requested changes
## Hi @XsidX,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️  
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 19:13 UTC, julie-ify commented on src/index.js
> +});
- [ ] Kindly add this functionality in a function and call the function when the page loads. You can check this [link](https://www.w3schools.com/jsref/event_onload.asp#:~:text=The%20onload%20event%20occurs%20when,CSS%20files%2C%20etc.) to learn how to do this.

2022-07-04 19:13 UTC, julie-ify commented on README.md
- [ ] There is a typo error at the beginning of this sentence, you have `n` but I guess you wanted to type `In`. Kindly fix it.

2022-07-05 06:18 UTC, Ismailco approved these changes
### Hi @XsidX, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 06:18 UTC, merged